### ISSUE TITLE
Example lua script error

### ISSUE THREAD

**Issue by JanSimek** [phiste/kengine#3]
When running the bundled [example/main.cpp](https://github.com/phiste/kengine/blob/master/example/main.cpp) I get the following error spammed in the terminal:

`[LuaSystem] Error in 'scripts/test.lua': lua: error: scripts/test.lua:2: attempt to call a nil value (field 'new')`

I am using Lua 5.3 on Arch linux.

**Comment by phiste** [comment]
Strange, seems like the Log type didn't register correctly with the LuaSystem. I'll try to run this when I get home and see what gives

**Comment by phiste** [comment]
Found the issue: I had modified the `Log` datapacket, but forgot to leave a default constructor, meaning it couldn't be created from Lua. Should work as expected with the latest commit, sorry for the inconvenience (I fixed another in test.lua while I was at it)

I need to find a simple and efficient way to unit test the LuaSystem :/
